FROM icecube2:installed as installed
LABEL com.halfmanhalftaco.fpga.temp=1

FROM fpga-base:centos6
COPY --from=installed /opt/icecube2 /opt/icecube2
CMD ["/opt/icecube2/iCEcube2"]
LABEL com.halfmanhalftaco.fpga.tool=icecube2
