FROM icecube2:installed as installed

FROM fpga-base 
ARG user_uid
ARG user_gid
ARG user_name
RUN echo $user_uid $user_gid $user_name
RUN 	groupadd -g $user_gid $user_name && \
	adduser -u $user_uid -g $user_uid -N -M -d /home/$user_name $user_name

COPY --from=installed /opt/icecube2 /opt/icecube2
CMD ["/opt/icecube2/iCEcube2"]
